#!/usr/bin/env bash

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

try_count=10
token=""
. /hive-config/rssh.keys

if [[ -z $rsa ]]; then 
	echo "Auth-keys not found. Exit"
	exit 1
fi


#install package
dpkg -s software-properties-common > /dev/null 2>&1
if [[ $? -ne 0 ]]; then
	apt-get update
	#DEBIAN_FRONTEND=noninteractive apt-get --yes --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
	DEBIAN_FRONTEND=noninteractive apt-get --yes --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install software-properties-common
fi


dpkg -s tmate > /dev/null 2>&1
if [[ $? -ne 0 ]]; then
	echo "Install tmate"
	add-apt-repository -y ppa:tmate.io/archive
	apt-get update
	apt-get -y install tmate
	
fi
####

#Config tmate
echo "set -g tmate-server-host \"$server_host\"" > /hive-config/rssh.conf
echo "set -g tmate-server-port $server_port" >> /hive-config/rssh.conf
echo "set -g tmate-server-rsa-fingerprint \"$rsa\"" >> /hive-config/rssh.conf
echo "set -g tmate-server-ecdsa-fingerprint \"$ecdsa\"" >> /hive-config/rssh.conf



#Add PATH
sed -i '/export PATH=/d' /home/user/.profile
sed -i '/motd/i\export PATH=\"\$PATH:\/hive\/bin:\/hive\/sbin\"' /home/user/.profile

#Check and gen ssh-keys
if [[ ! -f /root/.ssh/id_rsa ]]; then
	echo -e 'y\n' | ssh-keygen -f /root/.ssh/id_rsa -t rsa -N '' > /dev/null 2>&1
fi


function stop_tmate {
	killall -s 9 tmate > /dev/null 2>&1
	sleep 1
	[[ -f /tmp/*tmate.sock ]] && rm -f /tmp/*tmate.sock
	}

function start_tmate {
	stop_tmate
	tmate -f /hive-config/rssh.conf -S /tmp/tmate.sock new-session -d
	ssh_string=""
	for (( i=0; i < $try_count; i++ ))
	do
		ssh_string=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
		[[ ! -z $ssh_string ]] && break
		sleep 1
	done
	
	if [[ -z $ssh_string ]]; then
		echo "Error connect to tunnel-server. Exit"
		stop_tmate
		exit 1
	fi
	
	token=$(echo $ssh_string | awk '{print $3}' | awk -F @ '{print $1}')
	web_string=$web_host"?"$token

	echo
	echo "Web-link:"
	echo $web_string
	echo 
	echo "Direct ssh-connect address:"
	echo $ssh_string
	echo
}


function restart_tmate {
	stop_tmate
	start_tmate
}

function usage {
	echo "Usage: hive-rssh start|stop|restart"
	}
	
case $1 in
	start)
		start_tmate
	;;
	stop)
		stop_tmate
	;;
	restart) 
		restart_tmate
	;;
	*)
		usage
	;;
esac
